#SITE DETAILS
site_name: My SRE Journey
site_author: Satheesh Pandian

#REPO DETAILS
repo_url: https://github.com/mysrejourney/mkdocs
repo_name: mysrejourney/mkdocs

#CONFIGURATION
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.tabs.link
  hide:
    - toc
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: pink
      accent: lime

#PAGE NAVIGATION
nav:
  - Home: "index.md"
  - Bash:
      - Conditional Statment: "bash/condition-statement.md"
      - Primary Expression: "bash/primary-expression.md"
      - Advanced Conditional: "bash/advanced-if-else.md"
      - Looping Concepts: "bash/looping-concepts.md"
      - For Loop: "bash/for-loop.md"
      - While Loop: "bash/while-loop.md"
      - Until Loop: "bash/until-loop.md"
      - IFS: "bash/ifs.md"
      - Special Parameters: "bash/special-parameters.md"
      - Stream Editor (sed): "bash/sed.md"
  - HTML:
      - Introduction: "html/introduction.md"
      - Template: "html/web-pages.md"
      - Important Tags: "html/important-tags.md"
  - CSS:
      - Introduction: "css/intro.md"
      - Selectors: "css/selector.md"
      - Colors: "css/color.md"
      - Order of Style: "css/cascade-priority.md"
  - Terraform:
      - Infrastructure As Code: "terraform/iac.md"
      - Introduction: "terraform/intro.md"
      - HCL: "terraform/commands.md"
      - Basics: "terraform/basics.md"
      - Terraform State:  "terraform/state.md"
      - Basic Commands: "terraform/commands.md"
      - Work with Terraform: "terraform/work_terraform.md"
      - Terraform in AWS: "terraform/terraform_in_aws.md"
  - K8s:
      - Architecture: "k8s/k8-arch.md"
      - ContainerD: "k8s/containerd.md"
      - Basics: "k8s/basics.md"
      - Configuration: "k8s/config.md"
      - Observability: "k8s/observability.md"
      - Imperative Commands: "k8s/imperative-commands.md"
      - Deployment Strategy: "k8s/deploy-strategy.md"
      - Services: "k8s/services.md"
      - Jobs: "k8s/jobs.md"
      - Cron Jobs: "k8s/cron-job.md"
      - Multi Containers: "k8s/multi-containers.md"
      - Persistent Volume: "k8s/persistent-volume.md"
      - Network Policy: "k8s/network-policy.md"
      - Security Context: "k8s/security-context.md"
      - Requests & Limits: "k8s/requests-limits.md"

  - Helm:
      - Introduction: "helm/intro.md"
      - Basic Commands: "helm/basic-commands.md"
      - Creating Chart: "helm/create-chart.md"
      - Functions: "helm/functions.md"
      - Conditions: "helm/conditions.md"
      - Chart Hooks: "helm/chart-hooks.md"

  - Ansible:
      - Introduction: "ansible/intro.md"

  - Kafka:
      - Introduction: "kafka/intro.md"

  - Observability:
      - Introduction: "observability/intro.md"
      - Promtheus: "observability/prometheus-intro.md"

  - Tips and Tricks:
      - Shell: "tips/shell-script.md"

#SOCIAL MEDIA ICONS
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mysrejourney/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/satheesh-j-950671224/

markdown_extensions:
  - toc:
      permalink: false
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - glightbox
  - search

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2023 <a href="https://github.com/mysrejourney/"  target="_blank" rel="noopener">Satheesh Pandian</a>