#SITE DETAILS
site_name: My SRE Learning Journey
site_author: Satheesh Pandian

#REPO DETAILS
repo_url: https://github.com/mysrejourney/mkdocs
repo_name: mysrejourney/mkdocs

#CONFIGURATION
theme:
  name: material
  font:
    text: Roboto Mono
    code: Roboto Mono
    typeface: 700
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.tabs.link
  hide:
    - toc
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
      primary: black
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
      primary: pink
      accent: lime

#PAGE NAVIGATION
nav:
  - Getting Started: "index.md"
  - Bash:
      - Conditional Statment: "bash/condition-statement.md"
      - Primary Expression: "bash/primary-expression.md"
      - Advanced Conditional: "bash/advanced-if-else.md"
      - Looping Concepts: "bash/looping-concepts.md"
      - For Loop: "bash/for-loop.md"
      - While Loop: "bash/while-loop.md"
      - Until Loop: "bash/until-loop.md"
      - IFS: "bash/ifs.md"
      - Special Parameters: "bash/special-parameters.md"
  - HTML:
      - Introduction: "html/introduction.md"
      - Template: "html/web-pages.md"
      - Important Tags: "html/tags.md"
  - Tips and Tricks:
      - Shell: "tips/shell-script.md"

#SOCIAL MEDIA ICONS
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/mysrejourney/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/satheesh-pandian-950671224/

markdown_extensions:
  - toc:
      permalink: false
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - glightbox
  - search

extra_css:
  - stylesheets/extra.css

copyright: |
  &copy; 2023 <a href="https://github.com/mysrejourney/"  target="_blank" rel="noopener">Satheesh Pandian</a>